[2021-06-16 07:07:23 +0000] [22474] [INFO] Starting gunicorn 20.1.0
[2021-06-16 07:07:23 +0000] [22474] [INFO] Listening at: http://0.0.0.0:3000 (22474)
[2021-06-16 07:07:23 +0000] [22474] [INFO] Using worker: sync
[2021-06-16 07:07:23 +0000] [22477] [INFO] Booting worker with pid: 22477
[2021-06-16 07:12:53 +0000] [22474] [INFO] Handling signal: hup
[2021-06-16 07:12:53 +0000] [22474] [INFO] Hang up: Master
[2021-06-16 07:12:53 +0000] [22474] [WARNING] Worker with pid 22477 was terminated due to signal 1
[2021-06-16 07:12:53 +0000] [22547] [INFO] Booting worker with pid: 22547
[2021-06-16 19:48:28 +0430] [22547] [ERROR] Error handling request /api/account/send-email
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 20:19:21 +0430] [22547] [ERROR] Error handling request /api/chat/show/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 20:19:35 +0430] [22547] [ERROR] Error handling request /api/chat/show/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:12:14 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:12:17 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:12:21 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:12:26 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:12:33 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:12:42 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:12:52 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:13:02 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:13:12 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:13:22 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:13:44 +0430] [22547] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 16:44:03 +0000] [22474] [INFO] Handling signal: term
[2021-06-16 21:14:03 +0430] [22547] [INFO] Worker exiting (pid: 22547)
[2021-06-16 16:44:03 +0000] [22474] [INFO] Shutting down: Master
[2021-06-16 16:48:36 +0000] [23544] [INFO] Starting gunicorn 20.1.0
[2021-06-16 16:48:36 +0000] [23544] [INFO] Listening at: http://0.0.0.0:8001 (23544)
[2021-06-16 16:48:36 +0000] [23544] [INFO] Using worker: sync
[2021-06-16 16:48:36 +0000] [23547] [INFO] Booting worker with pid: 23547
[2021-06-16 16:48:50 +0000] [23544] [INFO] Handling signal: term
[2021-06-16 21:18:50 +0430] [23547] [INFO] Worker exiting (pid: 23547)
[2021-06-16 16:48:50 +0000] [23544] [INFO] Shutting down: Master
[2021-06-16 16:48:59 +0000] [23551] [INFO] Starting gunicorn 20.1.0
[2021-06-16 16:48:59 +0000] [23551] [INFO] Listening at: http://0.0.0.0:8001 (23551)
[2021-06-16 16:48:59 +0000] [23551] [INFO] Using worker: sync
[2021-06-16 16:48:59 +0000] [23554] [INFO] Booting worker with pid: 23554
[2021-06-16 16:49:06 +0000] [23557] [INFO] Starting gunicorn 20.1.0
[2021-06-16 16:49:06 +0000] [23557] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:06 +0000] [23557] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:07 +0000] [23557] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:07 +0000] [23557] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:08 +0000] [23557] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:08 +0000] [23557] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:09 +0000] [23557] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:09 +0000] [23557] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:10 +0000] [23557] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:10 +0000] [23557] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:11 +0000] [23560] [INFO] Starting gunicorn 20.1.0
[2021-06-16 16:49:11 +0000] [23560] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:11 +0000] [23560] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:11 +0000] [23557] [ERROR] Can't connect to ('0.0.0.0', 8001)
[2021-06-16 16:49:12 +0000] [23560] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:12 +0000] [23560] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:13 +0000] [23560] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:13 +0000] [23560] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:14 +0000] [23560] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:14 +0000] [23560] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:15 +0000] [23560] [ERROR] Connection in use: ('0.0.0.0', 8001)
[2021-06-16 16:49:15 +0000] [23560] [ERROR] Retrying in 1 second.
[2021-06-16 16:49:16 +0000] [23560] [ERROR] Can't connect to ('0.0.0.0', 8001)
[2021-06-16 16:53:51 +0000] [23551] [INFO] Handling signal: term
[2021-06-16 21:23:51 +0430] [23554] [INFO] Worker exiting (pid: 23554)
[2021-06-16 16:53:52 +0000] [23551] [INFO] Shutting down: Master
[2021-06-16 16:55:32 +0000] [23741] [INFO] Starting gunicorn 20.1.0
[2021-06-16 16:55:32 +0000] [23741] [INFO] Listening at: http://0.0.0.0:3000 (23741)
[2021-06-16 16:55:32 +0000] [23741] [INFO] Using worker: sync
[2021-06-16 16:55:32 +0000] [23744] [INFO] Booting worker with pid: 23744
[2021-06-16 21:27:00 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:27:04 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:27:08 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:27:14 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:27:21 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:27:30 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:27:40 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:27:50 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:28:01 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:28:11 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:28:22 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:28:43 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:16 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:16 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:23 +0430] [23744] [ERROR] Error handling request /ws/api/chat/2/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:26 +0430] [23744] [ERROR] Error handling request /ws/api/chat/1/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:30 +0430] [23744] [ERROR] Error handling request /ws/api/chat/4/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:35 +0430] [23744] [ERROR] Error handling request /ws/api/chat/5/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:40 +0430] [23744] [ERROR] Error handling request /ws/api/chat/6/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:29:59 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:30:58 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:31:58 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:32:08 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:33:08 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:33:18 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:34:18 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:34:28 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:35:38 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:36:38 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:36:48 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:37:56 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:39:04 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:40:11 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:41:17 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:42:25 +0430] [23744] [ERROR] Error handling request /ws/api/chat/3/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:43:37 +0430] [23744] [ERROR] Error handling request /ws/api/chat/1/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:44:04 +0430] [23744] [ERROR] Error handling request /ws/api/chat/1/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 21:44:44 +0430] [23744] [ERROR] Error handling request /ws/api/chat/1/
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 136, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 179, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
TypeError: __call__() missing 1 required positional argument: 'send'
[2021-06-16 17:15:36 +0000] [23741] [INFO] Handling signal: term
[2021-06-16 21:45:36 +0430] [23744] [INFO] Worker exiting (pid: 23744)
[2021-06-16 17:15:36 +0000] [23741] [INFO] Shutting down: Master
2021-06-17 10:50:30,688 INFO     Starting server at tcp:port=3000:interface=0.0.0.0
2021-06-17 10:50:30,689 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2021-06-17 10:50:30,689 INFO     Configuring endpoint tcp:port=3000:interface=0.0.0.0
2021-06-17 10:50:30,690 INFO     Listening on TCP address 0.0.0.0:3000
2021-06-17 11:05:07,669 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-06-17 12:32:04,325 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-06-17 12:32:08,331 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-10 22:30:44,367 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:24:30,801 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:28:14,045 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:29:08,857 ERROR    There was an exception deleting the file `chats/documents/download_1.jpg` on field `chat.message.file`
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/django_cleanup/handlers.py", line 96, in run_on_commit
    file_.delete(save=False)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 105, in delete
    self.storage.delete(self.name)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 304, in delete
    os.remove(name)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/SoftwareCheetahsBackEnd/media_cdn/chats/documents/download_1.jpg'
2021-07-11 00:29:47,804 ERROR    There was an exception deleting the file `chats/documents/follow-quiz.txt` on field `chat.message.file`
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/django_cleanup/handlers.py", line 96, in run_on_commit
    file_.delete(save=False)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/django/db/models/fields/files.py", line 105, in delete
    self.storage.delete(self.name)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/django/core/files/storage.py", line 304, in delete
    os.remove(name)
PermissionError: [Errno 13] Permission denied: '/home/ubuntu/SoftwareCheetahsBackEnd/media_cdn/chats/documents/follow-quiz.txt'
2021-07-11 00:33:33,392 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:34:25,449 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:34:45,474 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:38:44,744 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:52:53,671 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:54:28,773 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 00:56:08,890 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 01:04:07,416 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 01:30:34,143 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 01:30:34,144 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 12:50:19,467 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 14:14:38,871 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 14:14:46,879 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
2021-07-11 14:15:30,931 ERROR    Exception inside application: disconnect() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/routing.py", line 160, in __call__
    send,
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    await dispatch(result)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/home/ubuntu/SoftwareCheetahsBackEnd/venv/lib/python3.6/site-packages/channels/generic/websocket.py", line 240, in websocket_disconnect
    await self.disconnect(message["code"])
TypeError: disconnect() takes 1 positional argument but 2 were given
